### ISSUE TITLE
mobx 2.7.0

### ISSUE THREAD

**Issue by chompy18** [500tech/ng2-mobx#5]
When installing ng2-mobx with npm, it also installs mobx 2.6.0.
Mobx 2.7.0 is already released, and it includes quite a few bug fixes and features.

Please update the mobx dependency

**Comment by mweststrate** [comment]
Maybe make Mobx a peer dependency like angular?

**Comment by chompy18** [comment]
@mweststrate  That is what I did, but I figured since it is already bundled, might as well update to the latest version. That way, if there are any modifications that affect ng2-mobx you'd catch it in tests.

**Comment by adamkleingit** [comment]
Done!
Check out 1.2.0
Also updated target compilation to ES5 instead of ES6
