### ISSUE TITLE
Host Directive or base Component

### ISSUE THREAD

**Issue by hccampos** [500tech/ng2-mobx#6]
It would be super nice to get rid of the wrapping component (which includes the mobx directive) and just extend a base component or add a directive to a host in order to support MobX.

When it comes to a directive for the host component, angular has this issue:  https://github.com/angular/angular/issues/8785

However, having a component that you extend to add MobX support should work. It would be kind of like the "onbserver" decorator in mobx-react.

**Comment by adamkleingit** [comment]
Hi,
the first attempt I made for ng2-mobx was using a decorator approach like mobx-react.
Unfortunately, there is no way to get the change detector ref of the component.

The only way I could solve it is by using a directive.

Also, overriding the onDestroy callback was a mess using a decorator, and using a directive it's straightforward.

BTW, what do you mean add a directive to a host?

**Comment by hccampos** [comment]
Well, I would like Angular to allow specifying it as..

```
@Component({
  selector: 'my-selector',
  template: `
    <div>...<div>
  `,
  hostDirectives: ['mobxAutorun'],
})
```

However, as the issue I linked above mentions, it is not currently feasible.

**Comment by adamkleingit** [comment]
I see.
I don't like extending a base class because you can only have one base class, and this will restrict the users.
Closing the issue unless you have a better idea on how to connect mobx to ng2
