### ISSUE TITLE
npm cdn missing directives

### ISSUE THREAD

**Issue by chompy18** [500tech/ng2-mobx#9]
Hey,

I wanted to play with ng2-mobx, so I used plunker and added the unpkg.com cdn url:
https://unpkg.com/ng2-mobx@1.2.2

but this returns the code with only references to the directive files, they are not bundled.

**Comment by adamkleingit** [comment]
How would you solve this? Webpack?

**Comment by aaronksaunders** [comment]
@adamkleingit @chompy18 just specify the full path

```javascript
      'ng2-mobx' : 'https://unpkg.com/ng2-mobx@1.2.2/dist/ng2-mobx.js'
```

see working plunker - http://plnkr.co/edit/S9BUJngjEiMFrg0kv4H1?p=preview

**Comment by adamkleingit** [comment]
Will solve in 1.2.3 using rollup

**Comment by adamkleingit** [comment]
Published 1.2.3 - can you verify?
https://unpkg.com/ng2-mobx@1.2.3/dist/ng2-mobx.umd.js

**Comment by chompy18** [comment]
Yup, seems to be working now. Nice!  :1st_place_medal:

**Comment by adamkleingit** [comment]
Awesome
